sudo: required

language: go

env:
- DEP_VERSION="0.5.0"

go:
  - go1.10.4
  - go1.11

before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep

install:
  - dep ensure
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/fzipp/gocyclo
  - . ./build/vanity.sh

script:
  - go install
  - golint $(go list -f {{.Dir}} ./... | grep -v /vendor/)
  - gocyclo -over 15 $(go list -f {{.Dir}}/*.go ./... | grep -v /vendor/)
  - go tool vet $(go list -f {{.Dir}}/*.go ./... | grep -v /vendor/)
  - ./build/codecov.sh
  - PBF_PROTO_BUFFER_SIZE=33554432 PBF_NCPU=4 go test -bench=. -benchtime=10s

after_success:
  - bash <(curl -s https://codecov.io/bash)
